### PR TITLE
fix bug when dest not provided

### PR DESCRIPTION
**Pull request by soumak77**

### CODE REVIEW

**Comment by gakimball** [comment]
Thanks! :)

**Comment by soumak77** [comment]
@gakimball could you release a new version with this change so that I can update some other libraries?

**Comment by gakimball** [comment]
Definitely. I can also make you a contributor if you ever want to make more changes.

**Comment by gakimball** [comment]
`hybrid-gulp@2.0.1` published.

**Comment by soumak77** [comment]
thanks!

**Pull request merged**
